# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: algorithms.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x61lgorithms.proto\x12\x04\x61lgo\",\n\x0e\x41\x64\x64NumsRequest\x12\x0c\n\x04num1\x18\x01 \x01(\x05\x12\x0c\n\x04num2\x18\x02 \x01(\x05\"\x1e\n\x0f\x41\x64\x64NumsResponse\x12\x0b\n\x03sum\x18\x01 \x01(\x05\"#\n\x14ReverseStringRequest\x12\x0b\n\x03str\x18\x01 \x01(\t\"-\n\x15ReverseStringResponse\x12\x14\n\x0creversed_str\x18\x01 \x01(\t\"\x1e\n\x0e\x46indMaxRequest\x12\x0c\n\x04nums\x18\x01 \x03(\x05\"\x1e\n\x0f\x46indMaxResponse\x12\x0b\n\x03max\x18\x01 \x01(\x05\x32\xc7\x01\n\x0b\x41lgoService\x12\x36\n\x07\x41\x64\x64Nums\x12\x14.algo.AddNumsRequest\x1a\x15.algo.AddNumsResponse\x12H\n\rReverseString\x12\x1a.algo.ReverseStringRequest\x1a\x1b.algo.ReverseStringResponse\x12\x36\n\x07\x46indMax\x12\x14.algo.FindMaxRequest\x1a\x15.algo.FindMaxResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'algorithms_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_ADDNUMSREQUEST']._serialized_start=26
  _globals['_ADDNUMSREQUEST']._serialized_end=70
  _globals['_ADDNUMSRESPONSE']._serialized_start=72
  _globals['_ADDNUMSRESPONSE']._serialized_end=102
  _globals['_REVERSESTRINGREQUEST']._serialized_start=104
  _globals['_REVERSESTRINGREQUEST']._serialized_end=139
  _globals['_REVERSESTRINGRESPONSE']._serialized_start=141
  _globals['_REVERSESTRINGRESPONSE']._serialized_end=186
  _globals['_FINDMAXREQUEST']._serialized_start=188
  _globals['_FINDMAXREQUEST']._serialized_end=218
  _globals['_FINDMAXRESPONSE']._serialized_start=220
  _globals['_FINDMAXRESPONSE']._serialized_end=250
  _globals['_ALGOSERVICE']._serialized_start=253
  _globals['_ALGOSERVICE']._serialized_end=452
# @@protoc_insertion_point(module_scope)
