# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: exchange.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x65xchange.proto\x12\x07handson\"\x1f\n\x0cHelloRequest\x12\x0f\n\x07request\x18\x01 \x01(\t\"!\n\rHelloResponse\x12\x10\n\x08response\x18\x01 \x01(\t2E\n\tHandshake\x12\x38\n\x05Hello\x12\x15.handson.HelloRequest\x1a\x16.handson.HelloResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'exchange_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_HELLOREQUEST']._serialized_start=27
  _globals['_HELLOREQUEST']._serialized_end=58
  _globals['_HELLORESPONSE']._serialized_start=60
  _globals['_HELLORESPONSE']._serialized_end=93
  _globals['_HANDSHAKE']._serialized_start=95
  _globals['_HANDSHAKE']._serialized_end=164
# @@protoc_insertion_point(module_scope)
